### ISSUE TITLE
Enhancement: Manual IP Entry

### ISSUE THREAD

**Issue by sfbg** [mkiol/Jupii#1]
Would it be possible to add the option to manually enter the IP of a DNLA client?

Context: my Kodi is not in the local network and Jupii cannot find it.

**Comment by mkiol** [comment]
Thank you for the report. I will consider this feature for the next release.

**Comment by sfbg** [comment]
Thank for adding it. I tried to test it, but a connection could not be set up... Probably it is a firewall issue on my side. Which port is Jupii trying to connect to?

**Comment by mkiol** [comment]
Very likely it is a NAT/firewall issue. 

Let me briefly describe the problem. To discover devices, UPnP uses SSDP protocol which is UDP based. Normally, client sends SSDP discover message to multicast address (239.255.255.250) in the local network. All UPnP devices respond directly to the client providing URL to XML description of the device capabilities (also via SSDP). This URL is needed to establish UPnP session that is HTTP based. If you can configure your router to pass 239.255.255.250 packets, Jupii should be able to discover your device from a different LAN without extra effort. If not, "add device manually" should help. Nevertheless, NAT/firewall pinhole is needed.

Let me explain how "add device manually" works:
1. Instead multicast, Jupii send SSDP discover directly to device IP address.
  ```<IP: phone_ip><port: random_udp_A> => <IP: device_ip><port: 1900> ```

2. Device responds but the source port **is a not a 1900** but new random UDP port. Firewall usually blocks that packet.
  ```<IP: device_ip><port: random_udp_B> => <IP: phone_ip><port: random_udp_A>```

Your firewall should be configured to pass any UDP from device_ip to phone_ip.

**Comment by mkiol** [comment]
Fixed in 49fc295886898f1a328314e627e6c7391f0ca8d3
