### ISSUE TITLE
not ship color / add some string to translate

### ISSUE THREAD

**Issue by ghost** [mkiol/Jupii#11]
![captura_20181105_001](https://user-images.githubusercontent.com/24536606/48029843-515ab380-e11d-11e8-8225-128ff09b78ac.png)
![captura_20180714_001](https://user-images.githubusercontent.com/24536606/48029860-59b2ee80-e11d-11e8-8508-66784efd113a.png)

**Comment by mkiol** [comment]
Ohh, right. I've missed it. Thanks.

**Comment by mkiol** [comment]
Fixed in 2.0.0 release.
