### ISSUE TITLE
Can't seek

### ISSUE THREAD

**Issue by dasDirksche** [mkiol/Jupii#2]
I can neither seek on the timeline nor use the fast forward/backward arrows. I adjust the timestep interval in the settings to 30s. I tried with mp3.

**Comment by dasDirksche** [comment]
p.s. On a Jolla 1

**Comment by mkiol** [comment]
Thank you for the report.

Likely, your UPnP device doesn't support Seek action. To check it for sure, the easiest way is to run Jupii from command line and save the debug log. 

E.g.:
```
[nemo@Sailfish ~]$ harbour-jupii &> log.txt
```

Here is example log entry gathered when I tested Jupii with Samsung TV. Device has supported only Play and Stop actions. 

```
[D] unknown:0 - CurrentTransportActions:
[D] unknown:0 -   actions: 36
[D] unknown:0 -   Next: 0
[D] unknown:0 -   Pause: 0
[D] unknown:0 -   Play: 4
[D] unknown:0 -   Previous: 0
[D] unknown:0 -   Seek: 0
[D] unknown:0 -   Stop: 32
```

**Comment by dasDirksche** [comment]
Thank you for the answer. 
If I use Donnie on Sailfish or the native music player on my BlackBerry  seeking  is working. So I don't think, that my Yamaha Network Player  doesn't support seeking action. But I will try to start Jupii from the command line. 

Greetings 

Am Donnerstag, 8. Februar 2018 schrieb Mkiol:

**Comment by mkiol** [comment]
Please do check it. If the issue is caused by some bug inside Jupii, I'm sure we will manage to resolve it.

BTW, What kind of Yamaha device do you have? I'm curious because I'm considering to add support of Yamaha's MusicCast API to the Jupii. Maybe your device could make use of it?

**Comment by dasDirksche** [comment]
Hi,
I use a R-N500 Network Receiver (R-N500DE20A2).

The logfile ends like this:

[D] unknown:0 - CurrentTransportActions:
[D] unknown:0 -   actions: 13
[D] unknown:0 -   Next: 1
[D] unknown:0 -   Pause: 0
[D] unknown:0 -   Play: 4
[D] unknown:0 -   Previous: 8
[D] unknown:0 -   Seek: 0
[D] unknown:0 -   Stop: 0
[D] unknown:0 - controlableChangedHandler
[D] unknown:0 - Pending controlable signal exists
[D] unknown:0 - Volume: 42
[D] unknown:0 - Emit delayed controlable signal
[D] onControlableChanged:297 - onControlableChanged: true
[D] onControlableChanged:298 -  playable: true
[D] onControlableChanged:299 -  stopable: false
[D] onControlableChanged:300 -  av.transportStatus: 1
[D] onControlableChanged:301 -  av.currentURI: 
http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[D] onControlableChanged:302 -  av.playSupported: true
[D] onControlableChanged:303 -  av.pauseSupported: false
[D] onControlableChanged:304 -  av.playSupported: true
[D] onControlableChanged:305 -  av.stopSupported: false

Do you need the hole logfile?

**Comment by dasDirksche** [comment]
Okay. The MusicCast App does not work with my Yamaha Receiver. I can use the NP Controller App. But you seem to be right, even in this App I can't seek. But why did it work with Donnie?

**Comment by mkiol** [comment]
So, the log shows that Seek is not supported. It doesn't mean that is not supported globally. Yamaha Receiver just doesn't allow Jupii to use that action.

Perhaps something is missing in a HTTP stream from Jupii to the receiver. The full log could help me in further troubleshooting. If you like, you can send it to my via e-mail (jupii[at]mkiol.net). I will look into Donie implementation as well.

**Comment by dasDirksche** [comment]
Works like a charm. Thank you very much

**Comment by mkiol** [comment]
Welcome. I'm glad I was able to help.
