### ISSUE TITLE
Can you cancel  all checked strings on Transifex?

### ISSUE THREAD

**Issue by dashinfantry** [mkiol/Jupii#25]

**Comment by mkiol** [comment]
For which language and why you need it?

**Comment by dashinfantry** [comment]
Chinese /汉语. To make it better  and change a mistake:) 星期三, 07 八月 2019, 02:16上午 +08:00 发件人 Mkiol  notifications@github.com :

**Comment by mkiol** [comment]
Ok. Feel free to make them better :-)
