### ISSUE TITLE
Unable to detect some DLNA players

### ISSUE THREAD

**Issue by dikonov** [mkiol/Jupii#27]
I have an Internet radio ("Jupiter" platform), which has an extra feature of being an upnp player. I used this functionality with Jupii before and it worked! 

However, the current version of Jupii fails to detect this player in the net and I cannot enter it manually. 

Facts:
1. Both the radio(player) and my Jolla phone with Jupii (server) are connected to the same wifi and the same subnet. I can ping the radio from the phone.
2. I disabled the firewall in the phone and there  is no filtration at the router.
3. Jupii detects other devices. a) My LG TV is seen as a player and Jupii is able to stream to the tv. b) minidlna server at my computer is visible too.
4. The radio can use other devices, such as the minidlna server at the computer.
5. The radio sees Jupii as a server, but displays a Connection timeout message, when I try to connect from its end (I repeat that there are no active firewalls in between).

6. PROBLEM: Jupii completely ignores the radio and never shows it in the list of available devices, even with the Show all devises opton ON. 

7. The radio is rather old and runs the same firmware it used when everything worked (no updates). The Jolla phone has passed through multiple updates of both Sailfish OS and Jupii.

This looks like a regression to me. 
Are there any fillters in the code that might reject one player and allow another?

**Comment by mkiol** [comment]
Thank you for your report.

Let me sum up. There are at least two issues:
1. Jupii does not detect Jupiter device
2. Jupiter device detects Jupii but you cannot connect ("Connection timeout" message)

To investigate the issues I need to see the log. In the most recent Jupii version (version 2.5.3 - OpenRepos) I've added option to enable logging to file. Please install it.

Do following steps:
1. Enable logging in Jupii (Settings page, last option)
2. Restart Jupii
3. Try to find devices (many times click on "Find devices")
4. Close Jupii
5. Copy /home/nemo/jupii.log fine to your computer. Rename it to something like jupii_issue_1.log.
6. Start Jupii
7. Try to find Jupii on your Jupiter device and try to connect (many times)
8. Close Jupii
9. Copy /home/nemo/jupii.log fine to your computer. Rename it to something like jupii_issue_2.log.

Please send both log files to jupii[at]mkiol.net.

**Comment by mkiol** [comment]
If problem still occurs, please provide the log and re-open this issue.

**Comment by dikonov** [comment]
I tested it with the new version and it seems to work, but(!) discovering this device takes a lot more time and tries than Kodi on my notebook. I had to run device discovery 5 times and manually reconnect the radio to the net before it appeared in jupii. The radio itself was connected all the time and played radio without problems before and after connection. 

Maybe the radio is slow and timeout in jupii is too short. Could the discovery be done in a background thread and last longer? Maybe UPNP devices could be cached and probed for availability before lengthy scanning?   

Here is part of the log (file attached
[jupii.log.gz](https://github.com/mkiol/Jupii/files/4305959/jupii.log.gz)
)
] :0 - ==> Visitor
[D] :0 -  Device
[D] :0 -   friendlyName: "Jupiter 6.2 002261b3626a"
[D] :0 -   deviceType: "urn:schemas-upnp-org:device:MediaRenderer:1"
[D] :0 -   UDN: "uuid:3dcc7100-f76c-11dd-87af-002261b3626a"
[D] :0 -   modelName: "Jupiter"
[D] :0 -   URLBase: "http://192.168.169.5:80/"
[D] :0 -  Service
[D] :0 -   controlURL: "AVTransport/control"
[D] :0 -   eventSubURL: "AVTransport/event"
[D] :0 -   SCPDURL: "AVTransport/scpd.xml"
[D] :0 -   serviceId: "urn:upnp-org:serviceId:AVTransport"
[D] :0 -   serviceType: "urn:schemas-upnp-org:service:AVTransport:1"
[D] :0 - ==> Visitor

**Comment by mkiol** [comment]
Thank you for the log.

Did you observe discovering delay for other UPnP devices as well? Kodi for instance.

In the recent version, I've added option to mark device as a favorite. All favorites devices are always available, therefore you can skip discovering phase. Of course it works only when IP address of your Jupiter device is always the same. It is sort of workaround but maybe it will resolve your issue.

**Comment by mkiol** [comment]
I can also provide configuration option to increase discovery timeout. Currently it is set to 5s.

https://github.com/mkiol/Jupii/blob/880ac0dba02659a627a071302dd26d48c0de866c/core/directory.cpp#L177

**Comment by dikonov** [comment]
I only have 3 devices. Kodi and LG TV LF650 are detected reliably and almost instanttly. 

Longer discovering delay is good, but (ideally) it should run in background. Already discovered devices should appear immediately and the user must be able to select/use them before the long discovery process finishes without waiting for "slow" devices unless they are needed.

**Comment by dikonov** [comment]
BTW, please, update the ru translation in the rpm ;)

**Comment by mkiol** [comment]
> Longer discovering delay is good, but (ideally) it should run in background. Already discovered devices should appear immediately and the user must be able to select/use them before the long discovery process finishes without waiting for "slow" devices to be found, unless they are needed.

I agree. I'm adding it to my (very long) TODO list.

**Comment by mkiol** [comment]
> BTW, please, update the ru translation in the rpm ;)

Thank you for the update. Will be in the next release.
