### ISSUE TITLE
Add Option to play YouTube Streams

### ISSUE THREAD

**Issue by EarthlingX** [mkiol/Jupii#36]
Currently Jupii supports the following online services:

- Bandcamp
- FOSDEM
- gPodder
- Icecast
- SomaFM
- SoundCloud
- TuneIn

Would it be possible to also add YouTube into the available services list? There are some live playlists on YouTube around, which would be great to listen to via Jupii. :-)

Thanks a lot for your efforts!

**Comment by mkiol** [comment]
Indeed Youtube would be great add-on for Jupii. Especially audio-only mode for playlists. I will investigate what implementation options are available in Youtube API.

I strongly recommend you checking  [microtube](https://openrepos.net/content/mistermagister/microtube) app. It delivers some support for Jupii. When Jupii is running (in a background), microtube should provide an option to forward content to Jupii's playlist.

**Comment by mkiol** [comment]
Closing the old issue report. YouTube is supported from version 2.14.
