### ISSUE TITLE
Unsupported Codec message

### ISSUE THREAD

**Issue by poetaster** [mkiol/Jupii#38]
The device on the other end is a buffalo nas. Works with linux and android devices. 

Media player complains about the jupii code. The logs from jupii don't say much but I get some erros:

Chunk one from juppi.log (excerpt)

`[D] 16:20:06.176 0x5b03384020 :0 - Headers:
[D] 16:20:06.176 0x5b03384020 :0 - "Content-Type" "image/jpeg"
[D] 16:20:06.176 0x5b03384020 :0 - "Content-Language" "en"
[D] 16:20:06.177 0x5b03384020 :0 - "Content-Length" "1963"
[D] 16:20:06.177 0x5b03384020 :0 - "Date" "Thu, 24 Feb 2022 15:20:04 GMT"
[D] 16:20:06.177 0x5b03384020 :0 - "Pragma" "no-cache"
[D] 16:20:06.177 0x5b03384020 :0 - "Cache-control" "no-cache"
[D] 16:20:06.177 0x5b03384020 :0 - "Connection" "keep-alive"
[D] 16:20:06.177 0x5b03384020 :0 - "EXT" ""
[D] 16:20:06.177 0x5b03384020 :0 - "Server" "Linux/2.x.x, UPnP/1.0, pvConnect UPnP SDK/1.0, TwonkyMedia UPnP SDK/1.1"
[D] 16:20:06.177 0x5b03384020 :0 - Response code: 200 "OK"
[D] 16:20:06.177 0x5b03384020 :0 - Saving album art to file
[D] 16:20:06.179 0x5b03384020 :0 - final id: QUrl("jupii://upnp/uuid%3A55076f6e-6b79-4d65-64b7-4ce67696f3df/0%241%2411%246975R2378763?jupii_cookie=1S2E7tpQ22")
[D] 16:20:06.180 0x5b02cf1830 :0 - addWorkerDone
[D] 16:20:06.452 0x5b02cf1830 :0 - Saving current playlist
[D] 16:20:06.482 0x5b02cf1830 :0 - onItemsLoaded
[D] 16:20:06.482 0x5b02cf1830 :0 - Set empty active URL
[D] 16:20:06.482 0x5b02cf1830 :0 - setActiveId: ""
[D] 16:20:06.483 0x5b02cf1830 :0 - setActiveItemIndex: -1 -1
[D] 16:20:06.483 0x5b02cf1830 :0 - doUpdate
[D] 16:20:06.483 0x5b02cf1830 :0 - updateDirectory
[D] 16:20:07.445 0x5b02cf1830 :0 - Update playlist
[D] 16:20:08.361 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.362 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:InternetGatewayDevice:1" friendly name: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.362 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:Layer3Forwarding:1"
[D] 16:20:08.363 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.364 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:WANConnectionDevice:1" friendly name: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.364 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1"
[D] 16:20:08.364 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.364 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:WANConnectionDevice:1" friendly name: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.364 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:WANIPConnection:1"
[D] 16:20:08.364 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.365 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:MediaServer:1" friendly name: "Jupii (Volla Phone)"
[D] 16:20:08.365 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:ContentDirectory:1"
[D] 16:20:08.365 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.366 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:MediaServer:1" friendly name: "Jupii (Volla Phone)"
[D] 16:20:08.366 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:ConnectionManager:1"
[D] 16:20:08.366 0x5b0325baf0 :0 - traverse end: 3
[W] 16:20:08.377 0x5b02cf1830 :0 - No icon for device: "Compal Broadband Networks, Inc CH6640"
[W] 16:20:08.386 0x5b02cf1830 :0 - No icon for device: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.388 0x5b02cf1830 :0 - Refreshing status for XC devices
[W] 16:20:20.028 0x5b02cf1830 modifyPageStack:110 - Error while modifying page stack: Error: No attached page to pop
[W] 16:20:20.029 0x5b02cf1830 :604 - file:///usr/lib64/qt5/qml/Sailfish/Silica/PageStack.js:604: Error: No attached page to pop
[W] 16:20:22.873 0x5b02cf1830 :0 - AVTransport service is not inited
[D] 16:20:22.874 0x5b02cf1830 :0 - State changed: Qt::ApplicationState(ApplicationInactive)
[W] 16:21:45.360 0x5b02cf1830 :0 - RenderingConrol is not inited!
[W] 16:21:45.361 0x5b02cf1830 :0 - RenderingControl service is not inited
[W] 16:21:45.361 0x5b02cf1830 :0 - RenderingConrol is not inited!
[W] 16:21:45.361 0x5b02cf1830 :0 - RenderingControl service is not inited
[W] 16:21:45.361 0x5b02cf1830 :0 - AVTransport service is not inited
[D] 16:21:45.361 0x5b02cf1830 :0 - State changed: Qt::ApplicationState(ApplicationActive)
[W] 16:23:07.955 0x5b02cf1830 :0 - AVTransport service is not inited
[D] 16:23:07.955 0x5b02cf1830 :0 - State changed: Qt::ApplicationState(ApplicationInactive)
`
Chunk 2 from from jupii_upnp.log

`[D] 16:20:06.176 0x5b03384020 :0 - Headers:
[D] 16:20:06.176 0x5b03384020 :0 - "Content-Type" "image/jpeg"
[D] 16:20:06.176 0x5b03384020 :0 - "Content-Language" "en"
[D] 16:20:06.177 0x5b03384020 :0 - "Content-Length" "1963"
[D] 16:20:06.177 0x5b03384020 :0 - "Date" "Thu, 24 Feb 2022 15:20:04 GMT"
[D] 16:20:06.177 0x5b03384020 :0 - "Pragma" "no-cache"
[D] 16:20:06.177 0x5b03384020 :0 - "Cache-control" "no-cache"
[D] 16:20:06.177 0x5b03384020 :0 - "Connection" "keep-alive"
[D] 16:20:06.177 0x5b03384020 :0 - "EXT" ""
[D] 16:20:06.177 0x5b03384020 :0 - "Server" "Linux/2.x.x, UPnP/1.0, pvConnect UPnP SDK/1.0, TwonkyMedia UPnP SDK/1.1"
[D] 16:20:06.177 0x5b03384020 :0 - Response code: 200 "OK"
[D] 16:20:06.177 0x5b03384020 :0 - Saving album art to file
[D] 16:20:06.179 0x5b03384020 :0 - final id: QUrl("jupii://upnp/uuid%3A55076f6e-6b79-4d65-64b7-4ce67696f3df/0%241%2411%246975R2378763?jupii_cookie=1S2E7tpQ22")
[D] 16:20:06.180 0x5b02cf1830 :0 - addWorkerDone
[D] 16:20:06.452 0x5b02cf1830 :0 - Saving current playlist
[D] 16:20:06.482 0x5b02cf1830 :0 - onItemsLoaded
[D] 16:20:06.482 0x5b02cf1830 :0 - Set empty active URL
[D] 16:20:06.482 0x5b02cf1830 :0 - setActiveId: ""
[D] 16:20:06.483 0x5b02cf1830 :0 - setActiveItemIndex: -1 -1
[D] 16:20:06.483 0x5b02cf1830 :0 - doUpdate
[D] 16:20:06.483 0x5b02cf1830 :0 - updateDirectory
[D] 16:20:07.445 0x5b02cf1830 :0 - Update playlist
[D] 16:20:08.361 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.362 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:InternetGatewayDevice:1" friendly name: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.362 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:Layer3Forwarding:1"
[D] 16:20:08.363 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.364 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:WANConnectionDevice:1" friendly name: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.364 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1"
[D] 16:20:08.364 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.364 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:WANConnectionDevice:1" friendly name: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.364 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:WANIPConnection:1"
[D] 16:20:08.364 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.365 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:MediaServer:1" friendly name: "Jupii (Volla Phone)"
[D] 16:20:08.365 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:ContentDirectory:1"
[D] 16:20:08.365 0x5b0325baf0 :0 - ==> new service found
[D] 16:20:08.366 0x5b0325baf0 :0 - Device| type: "urn:schemas-upnp-org:device:MediaServer:1" friendly name: "Jupii (Volla Phone)"
[D] 16:20:08.366 0x5b0325baf0 :0 - Service| type: "urn:schemas-upnp-org:service:ConnectionManager:1"
[D] 16:20:08.366 0x5b0325baf0 :0 - traverse end: 3
[W] 16:20:08.377 0x5b02cf1830 :0 - No icon for device: "Compal Broadband Networks, Inc CH6640"
[W] 16:20:08.386 0x5b02cf1830 :0 - No icon for device: "Compal Broadband Networks, Inc CH6640"
[D] 16:20:08.388 0x5b02cf1830 :0 - Refreshing status for XC devices
[W] 16:20:20.028 0x5b02cf1830 modifyPageStack:110 - Error while modifying page stack: Error: No attached page to pop
[W] 16:20:20.029 0x5b02cf1830 :604 - file:///usr/lib64/qt5/qml/Sailfish/Silica/PageStack.js:604: Error: No attached page to pop
[W] 16:20:22.873 0x5b02cf1830 :0 - AVTransport service is not inited
[D] 16:20:22.874 0x5b02cf1830 :0 - State changed: Qt::ApplicationState(ApplicationInactive)
[W] 16:21:45.360 0x5b02cf1830 :0 - RenderingConrol is not inited!
[W] 16:21:45.361 0x5b02cf1830 :0 - RenderingControl service is not inited
[W] 16:21:45.361 0x5b02cf1830 :0 - RenderingConrol is not inited!
[W] 16:21:45.361 0x5b02cf1830 :0 - RenderingControl service is not inited
[W] 16:21:45.361 0x5b02cf1830 :0 - AVTransport service is not inited
[D] 16:21:45.361 0x5b02cf1830 :0 - State changed: Qt::ApplicationState(ApplicationActive)
[W] 16:23:07.955 0x5b02cf1830 :0 - AVTransport service is not inited
[D] 16:23:07.955 0x5b02cf1830 :0 - State changed: Qt::ApplicationState(ApplicationInactive)
`

**Comment by mkiol** [comment]
Thanks for reporting. Indeed log doesn't reveal anything. Unfortunately the moment of playing attempt wasn't recorded.

Could you please precisely describe what the use-case is (e.g. steps) and provide full `jupii.log` (you can send it to me via e-mail if you don't want to enclose it on github)?

Log collecting steps:
1. enable logging to file
2. close and start Jupii
3. ==> do your test <==
4. close Jupii
5. get the `jupii.log` file

**Comment by poetaster** [comment]
Ok, here the logs made just now. 

 * Jupii open with logging on, 
 *  check playlist. 
 * Open media player, 
 * select playlist, 
 * try playing songs.
 
[jupii.log](https://github.com/mkiol/Jupii/files/8152195/jupii.log)

**Comment by mkiol** [comment]
Sorry for late reply.

I've checked the log and didn't find anything significant :/ I see that you added few items from Media Server (assuming this is NAS device) and nothing more. I don't see any attempt to connect to renderer device or play attempt.

Honestly, I still don't fully understand what you are trying to do. 

Please correct me. My understanding of your use-case is as follows:
- There is NAS device which can serve music files as UPnP Media Server
- There is "media player" which acts as UPnP Media Renderer. This "media player" is an app on your PC (e.g. VLC), right?
- You added few media items from NAS device to Jupii play queue (with Add->Media Server)
- With "media player" app you are trying to play items which are on Jupii's play queue, right?

**Comment by poetaster** [comment]
I think the problem is that I'm expecting the Jolla Media Player to handle this. I saved the playlist created in Jupii and that showed up with the local Media Player. The local Media Player app however can't handle the uris. VLC and co. on other machines talk to the NAS DLNA directly. For the latter, I don't see the use case with Jupii? I have DLNA clients everywhere except on SFOS?

I would beg the question why the playlists are showing up 'local' when they can't be used? It's a bit confusing.

**Comment by mkiol** [comment]
> I think the problem is that I'm expecting the Jolla Media Player to handle this. I saved the playlist created in Jupii and that showed up with the local Media Player. The local Media Player app however can't handle the uris.

Now everything is crystal clear :)

Indeed Jolla Media Player is not able to play "UPnP Media Server" items. The URL scheme is something only understandable to Jupii. But any other items (other that Media Server items) should be playable.

> For the latter, I don't see the use case with Jupii

The main (not the only one) use-case for Jupii is to play content stored on your phone on remote device like smart speakers, TV etc. Unfortunately right now you can't use Jupii to play (on the phone) content from Media Server (like NAS). You can't use your phone as, so called Media Renderer. This use case is not yet implemented.

You should try [Donnie](https://openrepos.net/content/wdehoog/donnie). This app allows you to play locally items from remote media server. It works well.

> I would beg the question why the playlists are showing up 'local' when they can't be used? It's a bit confusing.

Playlists are shown in 'Local' section because you can for instance create playlist containing your local music files (e.g. create playilist with Jolla Music Player) and than use this playlist in Jupii to play music on remote speaker and so on.

Very likely this confusion is because Jupii description is confusing. I should underline in more detail what you can do and what you can't do with this app. Sorry.

**Comment by poetaster** [comment]
> The main (not the only one) use-case for Jupii is to play content stored on your phone on remote device like smart speakers, TV etc. Unfortunately right now you can't use Jupii to play (on the phone) content from Media Server (like NAS). You can't use your phone as, so called Media Renderer. This use case is not yet implemented.

Of course! I keep thinking in the other direction because I store all music on a nas and use dlna clients. I hadn't thought about phone to Renderer. 


> You should try [Donnie](https://openrepos.net/content/wdehoog/donnie). This app allows you to play locally items from remote media server. It works well.

I've cloned it already :) It's a bit tricky since there is no aarch64 support and the libupnp it uses is dated. Perhaps you know what upnp library might be appropriate since there are some available from jolla? But, I've started looking at port although I only made a ticket 11 days ago.

**Comment by poetaster** [comment]
> Very likely this confusion is because Jupii description is confusing. I should underline in more detail what you can do and what you can't do with this app. Sorry.

Oh, don't be sorry, I think I just let my self be confused, and thanks for the work!

**Comment by mkiol** [comment]
> I've cloned it already :) It's a bit tricky since there is no aarch64 support and the libupnp it uses is dated. Perhaps you know what upnp library might be appropriate since there are some available from jolla?

Jupii also use `libupnp`. Binaries for aarch64 are [here](https://github.com/mkiol/Jupii/tree/master/libs/libupnpp/build/sfos-arm64).  But probably you can just simple re-use them. Donnie might expect specific version of this library.

Sources used for `libupnp` and `libupnpp` in Jupii:
https://framagit.org/medoc92/npupnp.git
https://framagit.org/medoc92/libupnpp.git

**Comment by poetaster** [comment]
Thank you very much! I'll try adding it as a static lib. and building for aarch64!
