### ISSUE TITLE
Upmpdcli and radio-browser

### ISSUE THREAD

**Issue by kan-ibal** [mkiol/Jupii#40]
There is radio-browser  implemented in upmpdcli already and i was able to make it works by installing python pyradios module using pip.
`pip install pyradios`
Now i can browse radio list and select a station but  then I get "item cannot be added" warning popup when I want to add selected station to playlist. What is the reason?

**Comment by mkiol** [comment]
Thanks for the report.

Could you please generate a log file for this issue? (Settings -> Enable logging)

**Comment by kan-ibal** [comment]
It looks like this part is valid for this issue:
`[D] 15:07:59.123 0x77a435b490 () - Initing
[D] 15:07:59.124 0x774a9f3fb0 () - Initing started
[D] 15:08:30.218 0x778dcd7fb0 () - making item: "jupii://upnp/...vYYYxxYYYx?jupii_cookie=XXXXXyXX"
[D] 15:08:30.219 0x778dcd7fb0 () - upnp url detected
[D] 15:08:30.220 0x778dcd7fb0 () - make upnp meta: "jupii://upnp/...vYYYxxYYYx"
[D] 15:08:30.220 0x778dcd7fb0 () - Initing
[D] 15:08:30.220 0x778dcd7fb0 () - Same service, init not needed
[D] 15:08:30.229 0x778dcd7fb0 () - item uri is empty
[W] 15:08:30.230 0x778dcd7fb0 () - no meta found
[W] 15:08:30.235 0x77a435b490 () - No icon for device: "UpMpd-Xperia10II-UPnP/AV"
[D] 15:08:30.253 0x77a435b490 () - add worker done
[W] 15:08:30.254 0x77a435b490 () - some urls are invalid and cannot be added to the playlist
[W] 15:08:30.255 0x77a435b490 () - no items to add to playlist
[W] 15:08:30.763 0x77a435b490 () - Id is invalid: ""
[W] 15:08:30.767 0x77a435b490 () - Id is invalid: ""
`

**Comment by mkiol** [comment]
Sorry for the late reply (I had a short vacation 🍹 )

There are two problems:

- upmpdcli (radio-browser plugin) does not accepts meta data query for single upnp item
- upmpdcli returns internet url instead of local url which is expected for items on media server

I'm preparing a fix for both issues.

**Comment by mkiol** [comment]
Resolved in 2.14.3 release.

**Comment by kan-ibal** [comment]
Thank you . An another Feature+ done :).
