### ISSUE TITLE
Cover missing from flac local file

### ISSUE THREAD

**Issue by batric** [mkiol/Jupii#41]
Playing flacs from a local path does not show the cover, the tag metadata are read correctly.

Cover is OK with mp3 ora aac files.

Regards
Riccardo

Ubuntu 22.04 italian
Version Jupii 2.14.4 flatpak

**Comment by mkiol** [comment]
Thanks for the report.

In current version cover picture extracting works only for MP3 and MP4 files (also AAC wrapped in MP4 container).

Fix: 44a607644a4a6a0f96ef4f00ae39c89b7e8b74f5

Change will be included in next version.

**Comment by mkiol** [comment]
The fix is included in v2.15.0
