### ISSUE TITLE
[Feature request] Native SFOS podcast apps integrations ?

### ISSUE THREAD

**Issue by Termitebug** [mkiol/Jupii#45]
How superusers or SFOS developers can add Jupii integration to apps? Because gPodder imho is not yet a polished gui (lacks autoplay, inbox, notifications, downloads location, etc).

Alternative apps; Podcatcher, PodQast.

**Comment by mkiol** [comment]
Thanks for the question. What type of integration are you thinking about?

To be honest, implemented integration with gPodder is quite limited. Using Jupii you can only browse and add already downloaded gPodder episodes. There is no support for any "podcast-friendly" features. Jupii just reads gPodder's configuration file to find out which episodes are downloaded and where files are stored.

Jupii supports also extensive [DBus API](https://github.com/mkiol/Jupii/blob/master/dbus/jupii.xml) that  can be used to add features like "Add to Jupii" or "Play in Jupii" in any other app. This kind of integration should be done in Podcatcher, or PodQast.
