### ISSUE TITLE
Better app store listing

### ISSUE THREAD

**Issue by bertob** [mkiol/Jupii#46]
The app store listing is almost in line with the [Flathub guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines), except for two small things:

- "Play audio, video and images on UPnP/DLNA devices" is longer than the recommended maximum (35 characters), maybe "Play media on UPnP/DLNA devices"?
- There are no [appstream brand colors](https://docs.flathub.org/blog/introducing-app-brand-colors/)

**Comment by mkiol** [comment]
Thanks so much for letting me know. I'm gonna fix this in the next release.

**Comment by mkiol** [comment]
Done in v2.15.0.
