### ISSUE TITLE
Adding files recursiverly

### ISSUE THREAD

**Issue by batric** [mkiol/Jupii#48]
Hello, it would be nice to ad an entire folder, including subfolders, to a Playqueue.

Regards

Riccardo

**Comment by mkiol** [comment]
Nice feature indeed. Thanks!

I will try to add it to the next version.

**Comment by mkiol** [comment]
Implemented in v2.15.0.

You can add a folder using Add->Folder, or with dragging and doping on play queue.

![image](https://github.com/user-attachments/assets/e493ef9f-3859-4116-9a14-6ff27d723ace)

91e7aa54cbe78452848aad60a8831b78ec35c6c3
