### ISSUE TITLE
Playback of FLAC radio streams not working

### ISSUE THREAD

**Issue by thomasiaticus** [mkiol/Jupii#50]
I cannot render FLAC radio streams (e.g. http://server9.streamserver24.com:18910/motherearth.klassik) to network speakers. MP3 streams work fine.

Overall, great app though! One of the few (if not the only one) Linux apps that actually detects and plays to my DLNA network speakers.

**Comment by Thestroyer** [comment]
Have you tried [GO2TV](https://github.com/alexballas/go2tv/)?

**Comment by mkiol** [comment]
@thomasiaticus Sorry for very late reply.

> I cannot render FLAC radio streams

Most likely, the rendered does not support FLAC format. Currently, Jupii does not transcode audio in live streams, it simply passes what was originally streamed to the speakers. 

Tested URL you provided and it works on well on the player that accepts FLAC.

BTW, it appears that "Mother Earth Klassik" is also available in MP3 format when searching radio.net :)

![image](https://github.com/user-attachments/assets/507e845d-e5a0-4571-bb4f-baa7c12277bf)

**Comment by mkiol** [comment]
Closing this issue. I think this problem was not related to Jupii, but rather to the lack of FLAC support on the Renderer side.
